export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const GET_POKEMON_NAME = "GET_POKEMON_NAME";
export const POST_POKEMON = "POST_POKEMON";
export const FILTERED_POKEMONS = "FILTERED_POKEMONS";
export const ORDERED_POKEMONS = "ORDERED_POKEMONS";
export const ALL_TYPES = "ALL_TYPES";